import { ITopic, IStudent, ITeacher, ICourseDetail } from "./type";

export const dataCourseT: ICourseDetail[] = [
  {
    course_id: "c123",
    title: "UI/UX Design",
    description: "UI/UX Design",
    image:
      "https://img.freepik.com/free-vector/3d-ux-design-website-icon-vector-isolated-white-background-3d-ux-ui-concept-cartoon-minimal-style-3d-icon-vector-render-illustration_726846-5949.jpg?w=740",
    price: 1000000,
    study: "UI/UX Design",
    requirement: "UI/UX Design",
    level: "UI/UX Design",
    language: "vietnamese",
    discount: 10000,
    ranking: 4.5,
    total_ranking: 100,
    total_enrollment: 100,
    total_lecture: 100,
    total_hour: 100,
    total_student: 100,
    teacher_id: "t123",
    topic_id: "topic123",
    teacher: {
      teacher_id: "t123",
      username: "Jionson whet",
      introduce:
        "I am a professional UI/UX designer with 10 years of experience.",
      subject: "Ui/UX thiết kế",
      educational_level: "12",
      email: "tu21591@gmail.com",
      phone: "123-456-7890",
      avatar: "fallback",
      course: "UI/UX Design",
      major: "IT",
      school: "HCMUTE",
      address_school: "HCM",
      amount: 100,
      totalStudent: 100,
      scoreReview: 4.5,
      totalReview: 100,
      totalCourse: 100,
      linkWeb: "https://jionsonwhet.com",
      linkFacebook: "",
      linkYoutube: "",
      linkLinkedin: "",
      user: {
        username: "tu21591",
        full_name: "Nguyễn Văn Tú",
        email: "",
        avatar: "",
        phone: "",
        role: "student",
        birthday: "",
        address: "",
        created_at: "",
        updated_at: "",
      },
    },
    user: {
      username: "tu21591",
      full_name: "Nguyễn Văn Tú",
      email: "",
      avatar: "",
      phone: "",
      role: "student",
      birthday: "",
      address: "",
      created_at: "",
      updated_at: "",
    },
  },
];
export const dataCategoryT: ITopic[] = [
  {
    topic_id: "topic123",
    title: "UI/UX Design",
    description: "UI/UX Design",
    course_count: 100,
  },
];
export const dataTeacherT: ITeacher[] = [
  {
    teacher_id: "t123",
    username: "Jionson whet",
    introduce:
      "I am a professional UI/UX designer with 10 years of experience.",
    subject: "Ui/UX thiết kế",
    educational_level: "12",
    email: "tu21591@gmail.com",
    phone: "123-456-7890",
    avatar: "fallback",
    course: "UI/UX Design",
    major: "IT",
    school: "HCMUTE",
    address_school: "HCM",
    amount: 100,
    totalStudent: 100,
    scoreReview: 4.5,
    totalReview: 100,
    totalCourse: 100,
    linkWeb: "https://jionsonwhet.com",
    linkFacebook: "",
    linkYoutube: "",
    linkLinkedin: "",
    user: {
      username: "tu21591",
      full_name: "Nguyễn Văn Tú",
      email: "",
      avatar: "",
      phone: "",
      role: "student",
      birthday: "",
      address: "",
      created_at: "",
      updated_at: "",
    },
  },
];
export const dataStudent: IStudent[] = [
  {
    id: "1231",
    education_level: "12",
    major: "IT",
    school: "HCMUTE",
    username: "zimb240",
    email: "zimb240@gmail.com",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "1232",
    education_level: "12",
    major: "IT",
    school: "HCMUTE",
    username: "zimb240",
    email: "zimb240@gmail.com",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "1233",
    education_level: "12",
    major: "IT",
    school: "HCMUTE",
    username: "zimb240",
    email: "zimb240@gmail.com",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "1234",
    education_level: "12",
    major: "IT",
    school: "HCMUTE",
    username: "zimb240",
    email: "zimb240@gmail.com",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: "1235",
    education_level: "12",
    major: "IT",
    school: "HCMUTE",
    username: "zimb240",
    email: "zimb240@gmail.com",
    createdAt: new Date(),
    updateAt: new Date(),
  },
];
export const dataSearch = {
  keywords: ["ux/ui library", "javascript", "c++ master", "fullstack"],
  course: dataCourseT,
};
