version: "3.9"

services:
  backend:
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: tumolaha/educonnect-server
    container_name: educonnect-server
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - "8080:3000"
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - public
      - private
  db:
    image: mysql:8.0.27
    # command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "27017:27017"
    networks:
      - private
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: tumolaha/educonnect-client
    container_name: educonnect-client
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - VITE_BASE_URL=/v1
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - public
networks:
  public:
    driver: bridge
  private:
    driver: bridge
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
secrets:
  db-password:
    file: ../db/password.txt
