import express from "express";
import userRoutes from "./user.route";
import cartRoutes from "./cart.route";
const courseRouter = require("./course.route");
import sessionRouter from "./session.route";
import lectureRouter from "./lecture.route";
import orderItemRouter from "./order_items.route";
import paymentRouter from "./payment.route";
const router = express.Router();
router.use("/user", userRoutes);
router.use("/course", courseRouter);
router.use("/session", sessionRouter);
router.use("/lecture", lectureRouter);
router.use("/order", orderItemRouter);
router.use("/cart", cartRoutes);
router.use("/payment", paymentRouter);
export default router;
