export const configRouter = {
  home: "/",
  login: "/login",
  signUp: "/signUp",
  registerInformation: "/register-information",
  course: "/course/:id",
  coursesCart: "/courses-cart",
  checkout: "/checkout",
  categoryFilter: "/category-filter",
  search: "/search",
  teacherCategory: "/teacher-category/:id",
  chat: "/chat",
  dashboardTeacher: "/teacher/dashboard",
  payout: "/teacher/payout",
  liststudent: "/teacher/liststudent",
  dashboardAdmin: "/admin/dashboard",
  reportSale: "/admin/reportsale",
  reportMember: "/admin/reportmember",
};
