export const configRouter = {
  home: "/",
  login: "/login",
  signUp: "/signUp",
  registerInformation: "/register-information",
  course: "/course/:id",
  coursesCart: "/courses-cart",
  checkout: "/checkout",
  categoryFilter: "/category-filter",
  search: "/search",
  teacherCategory: "/teacher-category/:id",
  chat: "/chat",
  dashboard: "/teacher/dashboard",
  payout: "/teacher/payout",
  liststudent: "/teacher/liststudent",
  myCourse: "/myCourse",
  learning: "/course/learn/:id",
  profile: "/profile",
};
